# docker-compose.yml (Modified for Portainer Stack Editor)

services:
  findmyapp:
    # Use the image you built and pushed (or built locally)
    # Make sure this image exists locally or on Docker Hub
    image: ghd182/findmy-app:latest
    container_name: findmyapp
    restart: unless-stopped
    ports:
      - "5000:5000" # Host:Container
    volumes:
      # --- USE ABSOLUTE HOST PATHS for your app's data ---
      # /absolute_path_to_findmy_app_folder/data:/app/data
      - /home/username/findmy-app/data:/app/data # EXAMPLE: CHANGE /home/username
      # - /home/username/findmy-app/.env:/app/.env # If using .env mount
    environment:
      # --- Core Flask/App Settings ---
      FLASK_ENV: production
      # Override with DEBUG if needed
      LOG_LEVEL: INFO
      # Set your timezone
      TZ: Europe/Amsterdam
      # Override if needed
      WAITRESS_THREADS: 8

      # --- Key Generation Seeds (KEEP THESE SECRET!) ---
      SECRET_SEED: "your-very-long-random-secret-phrase-for-sessions-portainer"
      FERNET_SEED: "another-different-long-random-secret-phrase-for-encryption-portainer"
      VAPID_SEED: "a-third-unique-long-random-phrase-for-push-keys-portainer"
      VAPID_CLAIMS_EMAIL: "mailto:user@email.com" # CHANGE ME

      # --- Anisette Server Configuration ---
      # Point to the internal anisette service defined below
      ANISETTE_SERVERS: "http://anisette:6969"

      # --- Other App Config ---
      DEFAULT_FETCH_INTERVAL_MINUTES: 15
      # Override fetch interval
      FETCH_INTERVAL_MINUTES: 15
      # Override battery threshold
      LOW_BATTERY_THRESHOLD: 20
      # Override notification cooldown (10 minutes)
      NOTIFICATION_COOLDOWN_SECONDS: 600
      # Override history retention
      NOTIFICATION_HISTORY_DAYS: 60
      # Override location history fetch duration     
      HISTORY_DURATION_DAYS: 14

    # --- Add dependency on the anisette service ---
    depends_on:
      - anisette

  # --- NEW Anisette Server Service ---
  anisette:
    image: dadoum/anisette-v3-server:latest # Official image
    container_name: anisette-server
    restart: unless-stopped
    # No external ports needed. Communication is internal via service name 'anisette'.
    # No volumes needed.
    # No environment variables needed.