"""Add last_seen_local to Device model

Revision ID: 40d3f921e7c6
Revises: 8843e2c97c02
Create Date: 2025-05-01 13:07:43.442599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d3f921e7c6'
down_revision = '8843e2c97c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_local', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_device_last_seen_local'), ['last_seen_local'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_last_seen_local'))
        batch_op.drop_column('last_seen_local')

    # ### end Alembic commands ###
