"""Initial migration with all models

Revision ID: 8843e2c97c02
Revises: 
Create Date: 2025-04-27 20:05:46.098873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8843e2c97c02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_internal', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('theme_mode', sa.String(length=10), nullable=True),
    sa.Column('theme_color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id_internal')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('apple_credential_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('apple_id', sa.String(length=120), nullable=False),
    sa.Column('apple_password_encrypted', sa.String(length=512), nullable=True),
    sa.Column('account_state_json', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apple_credential_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apple_credential_state_apple_id'), ['apple_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apple_credential_state_user_username'), ['user_username'], unique=True)

    op.create_table('device',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=5), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('last_battery_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_user_username'), ['user_username'], unique=False)

    op.create_table('geofence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geofence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geofence_user_username'), ['user_username'], unique=False)

    op.create_table('notification_history',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_history_user_username'), ['user_username'], unique=False)

    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=1024), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_username', 'endpoint', name='_user_endpoint_uc')
    )
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscription_user_username'), ['user_username'], unique=False)

    op.create_table('device_geofence_link',
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('geofence_id', sa.String(length=64), nullable=False),
    sa.Column('notify_entry', sa.Boolean(), nullable=False),
    sa.Column('notify_exit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'geofence_id')
    )
    op.create_table('geofence_device_status',
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('geofence_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'geofence_id')
    )
    op.create_table('notification_cooldown',
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('event_key', sa.String(length=100), nullable=False),
    sa.Column('last_sent_timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'event_key')
    )
    op.create_table('share',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_user_username'), ['user_username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_user_username'))
        batch_op.drop_index(batch_op.f('ix_share_expires_at'))
        batch_op.drop_index(batch_op.f('ix_share_device_id'))

    op.drop_table('share')
    op.drop_table('notification_cooldown')
    op.drop_table('geofence_device_status')
    op.drop_table('device_geofence_link')
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_username'))

    op.drop_table('push_subscription')
    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_history_user_username'))
        batch_op.drop_index(batch_op.f('ix_notification_history_timestamp'))

    op.drop_table('notification_history')
    with op.batch_alter_table('geofence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geofence_user_username'))

    op.drop_table('geofence')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_user_username'))

    op.drop_table('device')
    with op.batch_alter_table('apple_credential_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apple_credential_state_user_username'))
        batch_op.drop_index(batch_op.f('ix_apple_credential_state_apple_id'))

    op.drop_table('apple_credential_state')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
