# File: migrations/versions/a9c8b7d6e5f4_consolidate_android_device_fields.py
"""Consolidate android device fields

Revision ID: a9c8b7d6e5f4
Revises: 5a8b8bcdeeb1
Create Date: 2025-06-11 11:20:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9c8b7d6e5f4"
down_revision = "5a8b8bcdeeb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device", schema=None) as batch_op:
        # Add columns from the original e1b980186eba migration
        batch_op.add_column(
            sa.Column("scan_enabled", sa.Boolean(), server_default="1", nullable=False)
        )

        # Add columns from the original c5d8a9e7f0b1 migration
        batch_op.add_column(
            sa.Column("last_seen_by_android", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("android_device_status", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(
            sa.Column("android_battery_level", sa.Integer(), nullable=True)
        )

        # Create indexes for the new columns
        batch_op.create_index(
            batch_op.f("ix_device_last_seen_by_android"),
            ["last_seen_by_android"],
            unique=False,
        )
        batch_op.create_index(
            "ix_device_user_scan_enabled",
            ["user_username", "scan_enabled"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device", schema=None) as batch_op:
        # Drop indexes first
        batch_op.drop_index("ix_device_user_scan_enabled")
        batch_op.drop_index(batch_op.f("ix_device_last_seen_by_android"))

        # Drop columns in reverse order of creation
        batch_op.drop_column("android_battery_level")
        batch_op.drop_column("android_device_status")
        batch_op.drop_column("last_seen_by_android")
        batch_op.drop_column("scan_enabled")

    # ### end Alembic commands ###
