"""Add scan_enabled flag to Device model

Revision ID: e1b980186eba
Revises: 5a8b8bcdeeb1
Create Date: 2025-05-05 18:09:15.739566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b980186eba'
down_revision = '5a8b8bcdeeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_enabled', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.create_index('ix_device_user_scan_enabled', ['user_username', 'scan_enabled'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index('ix_device_user_scan_enabled')
        batch_op.drop_column('scan_enabled')

    # ### end Alembic commands ###
